package co.kruzr.bernoulli;

/**
 * Covers what to do in the event of a particular Setting being disabled.
 */
public enum SettingsDisabledPolicy {

    PROCEED,
    FAIL,

    IF_MISSING_THEN_ASK_AFTER_RATIONALE,

    IF_MISSING_THEN_ASK_WITHOUT_RATIONALE,

    IF_MISSING_THEN_ASK_AFTER_RATIONALE_IF_DENIED_THEN_PROCEED,

    IF_MISSING_THEN_ASK_AFTER_RATIONALE_IF_DENIED_THEN_FAIL,

    IF_MISSING_THEN_ASK_WITHOUT_RATIONALE_IF_DENIED_THEN_PROCEED,

    IF_MISSING_THEN_ASK_WITHOUT_RATIONALE_IF_DENIED_THEN_FAIL,

    IF_MISSING_THEN_ASK_AFTER_RATIONALE_IF_DENIED_THEN_REDIRECT_TO_SETTINGS;
}
